### PR TITLE
Basic template

### PR DESCRIPTION
**Pull request by wilson496**
Based this off of the Python starter snake. 

Feedback welcome.

### CODE REVIEW

**Comment by codeallthethingz** [comment]
Hey @wilson496 great start!

Have a look at the new snake specs to make sure the snake is valid

https://github.com/battlesnakeio/docs/blob/master/apis/snake/spec.yaml

For example, movement is now "up" "down" "left" "right"  and we don't currently support taunts.

**Comment by codeallthethingz** [comment]
@wilson496 Let us know if you want to continue this.

**Comment by wilson496** [comment]
Might be better if someone else takes this over, just in the interest of time.

Apologies for the delay.

**Comment by codeallthethingz** [comment]
Understood!

**Pull request closed without merging**
